# Generated by Django 5.0.6 on 2024-07-03 13:40

import django.core.files.storage.filesystem
from django.db import migrations, models

import bazis.core.utils.orm
import model_clone.mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=bazis.core.utils.orm.get_file_path, verbose_name='File')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('extension', models.CharField(blank=True, max_length=50, null=True, verbose_name='Extension')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Uploadable files',
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
