# Generated by Django 5.0.1 on 2025-02-12 13:39

import bazis.core.utils.orm
import django.core.files.storage.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=bazis.core.utils.orm.get_file_path, verbose_name='File'),
        ),
    ]
