# Generated by Django 6.1.1 on 2026-10-01 09:06

import bazis.contrib.uploadable.models_abstract
import bazis.core.utils.orm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadable", "0002_alter_fileupload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=bazis.contrib.uploadable.models_abstract.get_file_upload_storage,
                upload_to=bazis.core.utils.orm.get_file_path,
                verbose_name="File",
            ),
        ),
    ]
