# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.1.1 on 2026-10-01 09:06

import bazis.contrib.uploadable.models_abstract
import bazis.core.utils.orm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadable", "0002_alter_fileupload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=bazis.contrib.uploadable.models_abstract.get_file_upload_storage,
                upload_to=bazis.core.utils.orm.get_file_path,
                verbose_name="File",
            ),
        ),
    ]
